package model;

public enum Zanr {
	DRAMA("DRAMA"),
	PSIHOLOGIJA("PSIHOLOGIJA"),
	ZDRAVLJE("ZDRAVLJE"),
	DETEKTIVSKI("DETEKTIVSKI"),
	NAUCNA_FANTASTIKA("NAUCNA FANTASTIKA"),
	HOROR("HOROR"), PUTOPISI("PUTOPISI"), 
    FANTAZIJA("FANTAZIJA"),
    EDUKACIJA("EDUKACIJA"),
    DECIJE("DECIJE"),
    ISTORIJSKI("ISTORIJSKI"),
    POEZIJA("POEZIJA"),
    BIOGRAFIJA("BIOGRAFIJA"),
    KUVARI("KUVARI"),
    UMETNOST("UMETNOST"),
    MOTIVACIJA_I_INSPIRACIJA("MOTIVACIJA I INSPIRACIJA"),
    LJUBAVNI("LJUBAVNI"),
    MARKETING_I_MENADZEMENT("MARKETING I MENADZMENT"),
    KLASICI("KLASICI"), SPORT("SPORT"),
    INTERNET_I_RACUNARI("INTERNET I RACUNARI");
	
	private String zanr;
	
	public String getAction() {
		return this.zanr;
	}
	private Zanr(String zanr) {
		this.zanr = zanr;
	}
}




